export type OrgSimplePreset = {
  key: string;
  title: string;
  group: "Conducción" | "Niveles" | "Formación" | "Familias" | "Administración" | "Soporte";
  area: string;
  formalRole: string;
  realFunction: string;
  description: string;
  color: string;
  icon: string;
};

/**
 * Biblioteca de cajas frecuentes para colegios APDES.
 * Son puntos de partida: al crearlas siguen siendo 100% editables.
 */
export const ORG_SIMPLE_PRESETS: OrgSimplePreset[] = [
  {
    key: "consejo-direccion",
    title: "Consejo de Dirección",
    group: "Conducción",
    area: "DIRECCION",
    formalRole: "Órgano de conducción institucional",
    realFunction: "Conducción colegiada y definición de criterios",
    description: "Define criterios, prioridades y acompaña la conducción general del colegio.",
    color: "#1C3A62",
    icon: "users",
  },
  {
    key: "direccion-general",
    title: "Dirección General",
    group: "Conducción",
    area: "DIRECCION",
    formalRole: "Dirección del colegio",
    realFunction: "Conducción general",
    description: "Conduce la vida institucional y articula las decisiones de los distintos equipos.",
    color: "#1C3A62",
    icon: "landmark",
  },
  {
    key: "nivel-inicial",
    title: "Nivel Inicial",
    group: "Niveles",
    area: "ACADEMICA",
    formalRole: "Dirección / Coordinación de Nivel Inicial",
    realFunction: "Conducción académica y operativa del Nivel Inicial",
    description: "Coordina la propuesta pedagógica, los equipos y el funcionamiento cotidiano del Nivel Inicial.",
    color: "#0f766e",
    icon: "graduation-cap",
  },
  {
    key: "equipo-directivo-inicial",
    title: "Equipo Directivo · Nivel Inicial",
    group: "Niveles",
    area: "ACADEMICA",
    formalRole: "Equipo Directivo de Nivel Inicial",
    realFunction: "Conducción del Nivel Inicial",
    description: "Reúne a las funciones de conducción que coordinan y acompañan la vida académica y formativa del Nivel Inicial.",
    color: "#0f766e",
    icon: "users",
  },
  {
    key: "nivel-primario",
    title: "Nivel Primario",
    group: "Niveles",
    area: "ACADEMICA",
    formalRole: "Dirección de Nivel Primario",
    realFunction: "Conducción académica y operativa del Nivel Primario",
    description: "Coordina la propuesta académica, el equipo docente y el funcionamiento cotidiano del Nivel Primario.",
    color: "#0f766e",
    icon: "graduation-cap",
  },
  {
    key: "equipo-directivo-primario",
    title: "Equipo Directivo · Nivel Primario",
    group: "Niveles",
    area: "ACADEMICA",
    formalRole: "Equipo Directivo de Nivel Primario",
    realFunction: "Conducción del Nivel Primario",
    description: "Reúne a las funciones de conducción que coordinan y acompañan la vida académica y formativa del Nivel Primario.",
    color: "#0f766e",
    icon: "users",
  },
  {
    key: "nivel-secundario",
    title: "Nivel Secundario",
    group: "Niveles",
    area: "ACADEMICA",
    formalRole: "Rectoría / Dirección de Nivel Secundario",
    realFunction: "Conducción académica y formativa del Nivel Secundario",
    description: "Coordina la propuesta académica, formativa y el funcionamiento cotidiano del Nivel Secundario.",
    color: "#0f766e",
    icon: "graduation-cap",
  },
  {
    key: "equipo-directivo-secundario",
    title: "Equipo Directivo · Nivel Secundario",
    group: "Niveles",
    area: "ACADEMICA",
    formalRole: "Equipo Directivo de Nivel Secundario",
    realFunction: "Conducción del Nivel Secundario",
    description: "Reúne a las funciones de conducción que coordinan y acompañan la vida académica y formativa del Nivel Secundario.",
    color: "#0f766e",
    icon: "users",
  },
  {
    key: "consejo-academico",
    title: "Consejo Académico",
    group: "Niveles",
    area: "ACADEMICA",
    formalRole: "Consejo Académico",
    realFunction: "Articulación de criterios académicos entre niveles",
    description: "Articula criterios académicos, prioridades pedagógicas y decisiones compartidas entre los distintos niveles.",
    color: "#0f766e",
    icon: "users",
  },
  {
    key: "secretaria-nivel",
    title: "Secretaría de Nivel",
    group: "Niveles",
    area: "ACADEMICA",
    formalRole: "Secretaría de Nivel",
    realFunction: "Gestión administrativa y organización cotidiana del nivel",
    description: "Organiza la documentación, agenda, comunicaciones y soporte administrativo del nivel.",
    color: "#0f766e",
    icon: "network",
  },
  {
    key: "equipo-docente",
    title: "Equipo Docente",
    group: "Niveles",
    area: "ACADEMICA",
    formalRole: "Equipo Docente",
    realFunction: "Enseñanza y acompañamiento de alumnos",
    description: "Reúne a los docentes responsables de la enseñanza y el acompañamiento cotidiano de los alumnos.",
    color: "#0f766e",
    icon: "users",
  },
  {
    key: "preceptoria",
    title: "Preceptoría",
    group: "Niveles",
    area: "ACADEMICA",
    formalRole: "Equipo de Preceptores",
    realFunction: "Organización y acompañamiento cotidiano de alumnos",
    description: "Acompaña la vida escolar cotidiana, la organización y el seguimiento de los alumnos.",
    color: "#0f766e",
    icon: "users",
  },
  {
    key: "coordinacion-ingles",
    title: "Coordinación de Inglés",
    group: "Niveles",
    area: "ACADEMICA",
    formalRole: "Coordinación de Inglés",
    realFunction: "Coordinación de la propuesta de inglés",
    description: "Coordina la enseñanza de inglés y articula el trabajo de los equipos docentes de los distintos niveles.",
    color: "#0f766e",
    icon: "graduation-cap",
  },
  {
    key: "coordinacion-academica",
    title: "Área Académica",
    group: "Niveles",
    area: "ACADEMICA",
    formalRole: "Coordinación académica",
    realFunction: "Acompañamiento de planificación, enseñanza y evaluación",
    description: "Acompaña la planificación, la enseñanza, la evaluación y la mejora de los procesos académicos.",
    color: "#0f766e",
    icon: "graduation-cap",
  },
  {
    key: "formacion-integral",
    title: "Formación Integral",
    group: "Formación",
    area: "FORMACION",
    formalRole: "Coordinación de Formación Integral",
    realFunction: "Articulación de tutorías y formación humana",
    description: "Articula tutorías, formación humana y acompañamiento de alumnos, familias y educadores.",
    color: "#7c3aed",
    icon: "book-open",
  },
  {
    key: "tutorias",
    title: "Tutorías",
    group: "Formación",
    area: "TUTORIA",
    formalRole: "Equipo tutorial",
    realFunction: "Acompañamiento personal de alumnos",
    description: "Acompaña personalmente a los alumnos y articula entrevistas, seguimiento y conversaciones con familias y docentes.",
    color: "#9333ea",
    icon: "handshake",
  },
  {
    key: "doe",
    title: "Orientación Escolar (DOE)",
    group: "Formación",
    area: "FORMACION",
    formalRole: "Departamento de Orientación Escolar",
    realFunction: "Acompañamiento psicopedagógico y orientación",
    description: "Acompaña las necesidades pedagógicas, psicológicas y de orientación de alumnos y equipos docentes.",
    color: "#7c3aed",
    icon: "heart-handshake",
  },
  {
    key: "capellania",
    title: "Capellanía",
    group: "Formación",
    area: "CAPELLANIA",
    formalRole: "Capellanía",
    realFunction: "Formación espiritual y acompañamiento",
    description: "Acompaña la formación espiritual de alumnos, familias y colaboradores.",
    color: "#166534",
    icon: "heart-handshake",
  },
  {
    key: "familias",
    title: "Familias",
    group: "Familias",
    area: "FAMILIA",
    formalRole: "Responsable de Familias",
    realFunction: "Vínculo y acompañamiento de familias",
    description: "Fortalece el vínculo con las familias y acompaña experiencias de incorporación, participación y comunidad.",
    color: "#d97706",
    icon: "users",
  },
  {
    key: "comunicacion",
    title: "Comunicación",
    group: "Familias",
    area: "COMUNICACION",
    formalRole: "Responsable de Comunicación",
    realFunction: "Comunicación institucional",
    description: "Ordena la comunicación institucional y facilita la circulación de información entre equipos y familias.",
    color: "#0284c7",
    icon: "megaphone",
  },
  {
    key: "comite-admisiones",
    title: "Comité de Admisiones",
    group: "Familias",
    area: "POSTULACIONES",
    formalRole: "Comité de Admisiones",
    realFunction: "Evaluación y coordinación de procesos de admisión",
    description: "Articula el proceso de admisiones y reúne la información necesaria para acompañar el ingreso de nuevas familias.",
    color: "#be123c",
    icon: "users",
  },
  {
    key: "postulaciones",
    title: "Postulaciones",
    group: "Familias",
    area: "POSTULACIONES",
    formalRole: "Responsable de Postulaciones",
    realFunction: "Ingreso y acompañamiento de nuevas familias",
    description: "Acompaña el ingreso de nuevas familias y articula su incorporación con las áreas involucradas.",
    color: "#be123c",
    icon: "pen-tool",
  },
  {
    key: "administracion",
    title: "Administración",
    group: "Administración",
    area: "ADMINISTRACION",
    formalRole: "Gestión administrativa",
    realFunction: "Procesos administrativos y documentación",
    description: "Ordena los procesos administrativos, la documentación y el soporte institucional.",
    color: "#334155",
    icon: "shield-check",
  },
  {
    key: "facturacion-cobranzas",
    title: "Facturación y Cobranzas",
    group: "Administración",
    area: "ADMINISTRACION",
    formalRole: "Facturación y Cobranzas",
    realFunction: "Gestión de facturación, cobranzas y seguimiento administrativo",
    description: "Gestiona la facturación, cobranzas y seguimiento administrativo de las familias.",
    color: "#334155",
    icon: "shield-check",
  },
  {
    key: "contabilidad-tesoreria",
    title: "Contabilidad y Tesorería",
    group: "Administración",
    area: "ADMINISTRACION",
    formalRole: "Contabilidad y Tesorería",
    realFunction: "Gestión contable y financiera",
    description: "Organiza la gestión contable, financiera y de tesorería del colegio.",
    color: "#334155",
    icon: "shield-check",
  },
  {
    key: "rrhh",
    title: "Recursos Humanos",
    group: "Administración",
    area: "ADMINISTRACION",
    formalRole: "Recursos Humanos",
    realFunction: "Gestión de personas y documentación laboral",
    description: "Acompaña la gestión de las personas, la documentación laboral y los procesos de Recursos Humanos.",
    color: "#334155",
    icon: "users",
  },
  {
    key: "operaciones",
    title: "Operaciones",
    group: "Administración",
    area: "OPERACIONES",
    formalRole: "Gestión operativa",
    realFunction: "Recursos, servicios e infraestructura",
    description: "Sostiene la organización cotidiana, los recursos, servicios e infraestructura necesarios para el funcionamiento institucional.",
    color: "#475569",
    icon: "building",
  },
  {
    key: "mantenimiento-servicios",
    title: "Mantenimiento y Servicios Generales",
    group: "Administración",
    area: "OPERACIONES",
    formalRole: "Mantenimiento y Servicios Generales",
    realFunction: "Mantenimiento, infraestructura y servicios",
    description: "Sostiene el mantenimiento, la infraestructura y los servicios necesarios para el funcionamiento del colegio.",
    color: "#475569",
    icon: "building",
  },
  {
    key: "limpieza-conserjeria",
    title: "Limpieza y Conserjería",
    group: "Administración",
    area: "OPERACIONES",
    formalRole: "Equipo de Limpieza y Conserjería",
    realFunction: "Orden, limpieza y soporte general",
    description: "Asegura la limpieza, el orden y el soporte general de los espacios institucionales.",
    color: "#475569",
    icon: "building",
  },
  {
    key: "recepcion",
    title: "Recepción",
    group: "Soporte",
    area: "OPERACIONES",
    formalRole: "Recepción institucional",
    realFunction: "Atención y soporte institucional",
    description: "Recibe y orienta a las familias y brinda soporte cotidiano a la comunidad educativa.",
    color: "#64748b",
    icon: "building",
  },
  {
    key: "tic",
    title: "TIC / Sistemas",
    group: "Soporte",
    area: "OPERACIONES",
    formalRole: "Soporte TIC",
    realFunction: "Tecnología y plataformas",
    description: "Da soporte a las herramientas tecnológicas y plataformas utilizadas por el colegio.",
    color: "#64748b",
    icon: "network",
  },
];

export function getOrgSimplePreset(key?: string | null) {
  if (!key) return null;
  return ORG_SIMPLE_PRESETS.find((preset) => preset.key === key) ?? null;
}
