export type PucaraHitoPerson = {
  sourceId: string;
  name: string;
  role: string;
  hours?: number;
  kind?: string;
};

export type PucaraHitoNode = {
  key: string;
  parentKey: string | null;
  title: string;
  role: string;
  principal?: PucaraHitoPerson | null;
  members?: PucaraHitoPerson[];
};

const p = (
  sourceId: string,
  name: string,
  role: string,
  hours?: number,
  kind = "Titular",
): PucaraHitoPerson => ({ sourceId, name, role, hours, kind });

// Copia estructural del organigrama del repositorio Tutardo23/hito.
// Se mantiene jerarquía, cargos, personas y equipos. Las relaciones transversales
// no forman parte de esta vista simple por decisión del proyecto actual.
export const PUCARA_HITO_NODES: PucaraHitoNode[] = [
  {
    key: "root",
    parentKey: null,
    title: "Consejo de Dirección",
    role: "Consejo Directivo",
    principal: null,
    members: [
      p("1", "Juan Manuel Romano", "Director General", 34),
      p("sec_6_37", "Hernan Ponce Veron", "Rector Nivel Secundario", 34),
      p("sec_18_7", "Fernando Casiva", "Vice Rector-Profesor Lengua", 34),
      p("p8", "Maria Eugenia Martin", "Recepción, Área Familia, Consejos de Dirección", 2),
    ],
  },
  {
    key: "1",
    parentKey: "root",
    title: "Director General",
    role: "Director General",
    principal: p("1", "Juan Manuel Romano", "Director General", 34),
  },
  {
    key: "2",
    parentKey: "1",
    title: "Directora Nivel Primario",
    role: "Directora Nivel Primario",
    principal: p("2", "Adriana Lozano", "Directora Nivel Primario", 31),
  },
  {
    key: "secretaria-primaria",
    parentKey: "2",
    title: "Secretaría de Nivel Primario",
    role: "Secretario de Nivel Primario",
    principal: p("secretaria-primaria", "César Juárez", "Secretario de Nivel Primario", 34),
  },
  {
    key: "4",
    parentKey: "2",
    title: "Equipo Docente (Primaria)",
    role: "Docentes",
    principal: null,
    members: [
      p("4-1", "Cristian Maurell", "Docente de grado", 12.7),
      p("4-2", "Fernando Chavez", "Docente de grado", 12.7),
      p("4-3", "Franco Orquera", "Docente de grado", 12.7),
      p("4-4", "Marcelo Sanchez", "Docente de grado", 12.7),
      p("4-5", "José María Torres", "Docente de grado", 12.7),
      p("4-6", "Marcelo Gutiérrez", "Docente de grado", 12.7),
      p("4-7", "David Gonzalez", "Docente de grado", 12.7),
      p("4-8", "Carlos Diaz", "Docente de grado", 12.7),
      p("4-9", "Matías Sosa", "Docente de grado", 12.7),
      p("4-10", "Sebastián Carrió", "Docente de grado", 12.7),
      p("4-11", "María Lourdes Clúa", "Docente de grado", 12.7),
      p("4-12", "Carolina Colombres Garmendia", "Docente de grado", 12.7),
    ],
  },
  {
    key: "5",
    parentKey: "2",
    title: "Profesores Especiales (Primaria)",
    role: "Educación Física / Música / Artística / Tecnología",
    principal: null,
    members: [
      p("5-1", "Rodolfo Camandona", "Profesor de Educación Física", 13.3),
      p("5-2", "Guillermo Sorucco", "Profesor de Educación Física", 8),
      p("5-3", "Carlos Camandona", "Profesor de Educación Física", 5.3),
      p("5-4", "Elisa Aguero", "Profesora de Música", 2.6),
      p("5-5", "Lourdes Fuentes Ortiz", "Profesora de Música", 4),
      p("5-6", "Ariel Medina", "Profesor de Educación Artística", 4),
      p("5-7", "Fabián Brizuela", "Profesor de Informática y Robótica", 12),
    ],
  },
  {
    key: "6",
    parentKey: "1",
    title: "Rector Nivel Secundario",
    role: "Rector - Profesor Salud y Adol.",
    principal: p("sec_6_37", "Veron Ponce Hernan", "Rector - Profesor Salud y Adol.", 34),
  },
  {
    key: "secretaria-secundaria",
    parentKey: "6",
    title: "Secretaría de Nivel Secundario",
    role: "Secretario de Nivel Secundario",
    principal: p("secretaria-secundaria", "Enrique Torino", "Secretario de Nivel Secundario", 34),
    members: [p("sec-apoyo-ana", "Ana María", "Apoyo Secretaría Secundaria", 20)],
  },
  {
    key: "8",
    parentKey: "6",
    title: "Equipo Docente (Secundaria)",
    role: "Profesores",
    principal: null,
    members: [
      p("sec_24_0", "Arnedo Daniel", "Profesor de Arte y Ed. Plastica", 16),
      p("sec_24_1", "Barrios Lucas", "Profesor de Fisica y Fe y Vida", 16),
      p("sec_6_3", "Brizuela Fabian", "Profesor TIC", 4),
      p("sec_12_4", "Camandona Carlos", "Profesor Educ Fis", 8),
      p("sec_8_5", "Camandona Rodolfo", "Prof Educ Fis", 5.33),
      p("sec_8_6", "Joaquin Dulcinea", "Profesora Química", 5.33),
      p("sec_18_7", "Casiva Fernando", "Vice Rector-Profesor Lengua", 34),
      p("sec_20_8", "Cisneros Matías", "Profesor Matemática", 13.33),
      p("sec_15_10", "Costas Carlos", "Profesor Geografía", 10),
      p("sec_13_11", "Di Risio Gabriel", "Profesor Administración", 8.67),
      p("sec_10_14", "Gallardo Juan Carlos", "Profesor Matemática", 6.67),
      p("sec_7_15", "Galván Javier", "Profesor Biología-Química", 4.67),
      p("sec_12_16", "Torres Matias", "Profesor Geografía", 8),
      p("sec_6_19", "Lix Kett Alvaro", "Profesor Derecho", 4),
      p("sec_18_20", "Lord Marcos", "Profesor Filosofía", 12),
      p("sec_14_21", "Mena Máximo", "Profesor Lengua", 9.33),
      p("sec_6_22", "Miglio Raúl", "Profesor Historia", 4),
      p("sec_22_24", "Pacheco Nicolás", "Profesor Ciudanía y Economía", 14.67),
      p("sec_15_25", "Parrado Emanuel", "Profesor Historia", 10),
      p("sec_6_26", "Pietro Ariel", "Profesor Historia", 4),
      p("sec_20_28", "Salcedo Ignacio", "Profesor Matemática", 13.33),
      p("sec_9_30", "Sierra Rodolfo", "Profesor Derecho", 6),
      p("sec_19_31", "Silva Santiago", "Profesor Biología - Química", 12.67),
      p("sec_8_32", "Soruco Guillermo", "Profesor Educ Fis", 5.33),
      p("sec_7_33", "Sosa Reto Rodolfo", "Profesor Administración", 4.67),
      p("sec_14_34", "Terán Emma", "Profesor Química", 9.33),
      p("sec_4_35", "Torino Enrique", "Secretario - Profesor Física", 2.67),
      p("sec_6_38", "Pinto Marcos", "Profesor Tecnología", 4),
    ],
  },
  {
    key: "9",
    parentKey: "6",
    title: "Equipo de Preceptores",
    role: "Preceptores",
    principal: null,
    members: [
      p("sec_4_2", "Bonfiglioli Tomás", "Pec- Profesor Educ Fis", 34),
      p("sec_14_9", "Cordoba Martín", "Pec- Profesor Tecnología", 34),
      p("sec_15_17", "Jiménez German", "Pec - Profesor Lengua", 34),
      p("sec_12_29", "Salica Martín", "Pec -Profesor Educ Fis", 34),
      p("sec_8_36", "Corvalán Claudio", "Pec - Profesor Fe y Vida", 34),
    ],
  },
  {
    key: "tutores",
    parentKey: "6",
    title: "Equipo de Tutores (Secundaria)",
    role: "Jefe de Tutores",
    principal: p("tutores", "Gerardo Tumini", "Jefe de Tutores", 14),
    members: [
      p("tutor1", "Emmanuel Parrado", "Tutor", 3),
      p("tutor2", "Jesús Guillermo Soruco", "Tutor", 1),
      p("tutor3", "Christian Kasem", "Tutor", 8),
      p("tutor4", "Carlos Marcelo Suárez Villafañe", "Tutor", 3),
      p("tutor5", "Luis Enrique Moscol Seminario", "Tutor", 5),
      p("tutor6", "Lucas Matías Barrios", "Tutor", 3),
      p("tutor7", "Marcos Lord Figueroa", "Tutor", 10),
      p("tutor8", "Matías Ortiz de Rozas", "Tutor", 5),
    ],
  },
  {
    key: "3",
    parentKey: "1",
    title: "Coordinadora Gral. de Inglés",
    role: "Coordinadora General de Inglés",
    principal: p("3", "Florentina Gonzales", "Coordinadora General de Inglés", 34),
  },
  {
    key: "3-1",
    parentKey: "3",
    title: "Equipo de Inglés (Primaria)",
    role: "Profesores de Inglés",
    principal: null,
    members: [
      p("3-1-1", "Martín Córdoba", "Profesor de Inglés", 16),
      p("3-1-2", "Priscila Mittelman", "Profesor de Inglés", 10.6),
      p("3-1-3", "Laura Lazarte", "Profesor de Inglés", 10.6),
      p("3-1-4", "Cristian López", "Profesor de Inglés", 16),
      p("3-1-5", "Sofía Filippini", "Profesor de Inglés", 5.3),
      p("3-1-6", "Salas María Florencia", "Profesor de Inglés", 5.3),
      p("3-1-7", "Karina Correa", "Profesor de Inglés", 5.3),
    ],
  },
  {
    key: "10",
    parentKey: "3",
    title: "Equipo de Inglés (Secundaria)",
    role: "Profesores de Inglés",
    principal: null,
    members: [
      p("sec_16_12", "Diaz Sorbello Pablo", "Profesor Inglés", 10.67),
      p("sec_12_13", "Fernandez Mercedes", "Profesor Inglés", 8),
      p("sec_8_18", "Lazarte Laura", "Profesor Inglés", 5.33),
      p("sec_14_23", "Nuñez Tadeo", "Profesor Inglés", 9.33),
      p("sec_16_27", "Ruiz Demetrio", "Profesor Inglés", 10.67),
    ],
  },
  {
    key: "taller-ingles",
    parentKey: "3",
    title: "Taller de Inglés",
    role: "Talleres complementarios de inglés",
    principal: null,
    members: [
      p("tall-1", "Carlos Martín Córdoba", "Profesor Taller de Inglés", 4),
      p("tall-2", "Cristian Gerardo López", "Profesor Taller de Inglés", 4),
      p("tall-3", "Pablo Alejandro Díaz Sorbello", "Profesor Taller de Inglés", 4),
      p("tall-4", "Priscilla Mittelmann", "Profesora Taller de Inglés", 4),
      p("tall-5", "Gustavo Maximiliano Roda", "Profesor Taller de Inglés", 4),
      p("tall-6", "María Marta Ale", "Profesora Taller de Inglés", 4),
      p("tall-7", "Karina Alejandra Correa", "Profesora Taller de Inglés", 4),
      p("tall-8", "Julieta Dulac", "Profesora Taller de Inglés", 4),
    ],
  },
  {
    key: "grupo-areas",
    parentKey: "1",
    title: "Áreas Transversales",
    role: "Agrupador de áreas",
    principal: null,
  },
  {
    key: "legal",
    parentKey: "grupo-areas",
    title: "Área Legal (Polo)",
    role: "Asesoría Legal (Tercerizada)",
    principal: p("legal", "Dra. Clara García Castellanos", "Asesoría Legal (Tercerizada)", 15, "Tercerizada"),
  },
  {
    key: "area-familia-polo",
    parentKey: "grupo-areas",
    title: "Área Familia, Comunicación y Postulaciones (Polo)",
    role: "Equipo unificado del Polo",
    principal: null,
    members: [
      p("maria-marta-rojas", "María Marta Rojas", "Directora Área Familia (Polo)", 31),
      p("maria-eugenia-martin", "María Eugenia Martín", "Colaboradora Área Familia (Polo)", 5),
      p("felicitas-del-frari", "Felicitas Del Frari", "Responsable de Postulaciones (Polo)", 29),
      p("agostina-garcia", "Agostina García Castro", "Comunicación y Promoción (Polo)", 20),
    ],
  },
  {
    key: "capellanes",
    parentKey: "grupo-areas",
    title: "Capellanía",
    role: "Formación espiritual y acompañamiento",
    principal: null,
    members: [
      p("galindo-jesus", "Jesús Galindo Bustos", "Capellán del Polo", 10),
      p("rant-andrej", "Andrej Rant", "Capellán del Polo", 31),
    ],
  },
  {
    key: "polo-adm-recepcion",
    parentKey: "grupo-areas",
    title: "Recepción",
    role: "Atención y soporte institucional",
    principal: null,
    members: [
      p("p8", "María Eugenia Martín", "Recepción Pucará", 25),
      p("p7", "Luciana Beverina", "Recepción Pucará (Tarde)", 14),
    ],
  },
  {
    key: "tic",
    parentKey: "grupo-areas",
    title: "TIC - Plataforma Colegium",
    role: "TIC - Plataforma Colegium",
    principal: p("p14", "Nicolás Torres", "TIC - Plataforma Colegium", 34),
  },
  {
    key: "area-admin",
    parentKey: "grupo-areas",
    title: "Administración (Polo)",
    role: "Administración (Polo)",
    principal: p("cristina-navarro", "Cristina Navarro Zaldarriaga", "Administración (Polo)", 34),
  },
  {
    key: "facturacion",
    parentKey: "area-admin",
    title: "Facturación y Cobranzas",
    role: "Gestión de cobranzas y administración contable",
    principal: null,
    members: [
      p("virginia-m", "Virginia Melhen", "Facturación y Tesorería", 34),
      p("mercedes-gp", "Mercedes García Posse", "Facturación y Cobranzas", 34),
      p("victoria-m", "Victoria Morano", "Facturación (Tercerizada)", 8, "Tercerizada"),
    ],
  },
  {
    key: "contabilidad",
    parentKey: "area-admin",
    title: "Contabilidad y Tesorería",
    role: "Gestión contable y financiera",
    principal: null,
    members: [
      p("cristina-zottoli", "Cristina Zottoli Z.", "Contabilidad y Tesorería", 25),
      p("virginia-melhen", "Virginia Melhen", "Facturación y Tesorería", 34),
    ],
  },
  {
    key: "rrhh",
    parentKey: "area-admin",
    title: "Recursos Humanos",
    role: "Gestión del personal y asesoría",
    principal: null,
    members: [
      p("dolores-k", "Dolores Kaese", "RRHH", 34),
      p("guillermina-c", "Guillermina Conti", "RRHH", 34),
    ],
  },
  {
    key: "mantenimiento",
    parentKey: "area-admin",
    title: "Mantenimiento, Operaciones y Servicios Generales",
    role: "Mantenimiento, Operaciones y Servicios Generales",
    principal: null,
    members: [
      p("varela-juan-pablo", "Juan Pablo Varela", "Mantenimiento, Operaciones y Servicios Generales", 34),
      p("lencina-maximiliano", "César Maximiliano Lencina", "Mantenimiento, Operaciones y Servicios Generales", 46.5),
    ],
  },
  {
    key: "limpieza",
    parentKey: "area-admin",
    title: "Personal de Limpieza y Conserjes",
    role: "Soporte institucional y mantenimiento general",
    principal: null,
    members: [
      p("cons1", "Carlos Walter Lencina", "Conserje", 46.5),
      p("cons2", "César Maximiliano Lencina", "Conserje", 46.5),
      p("cons3", "Álvaro Sebastián Samaquiri", "Conserje", 46.5),
      p("cons4", "Edgardo Enrique Rodríguez", "Conserje", 32),
      p("cons5", "Diego Alejandro Rodríguez", "Conserje", 40),
    ],
  },
  {
    key: "polo-doe",
    parentKey: "1",
    title: "Departamento de Orientación Escolar (DOE)",
    role: "Psicólogos y Psicopedagogos",
    principal: null,
  },
  {
    key: "doe-primaria",
    parentKey: "polo-doe",
    title: "DOE Nivel Primario",
    role: "Psicopedagoga DOE Primaria",
    principal: p("doe-primaria", "María Fioretti", "Psicopedagoga DOE Primaria", 12),
  },
  {
    key: "doe-secundaria",
    parentKey: "polo-doe",
    title: "DOE Nivel Secundario",
    role: "Psicopedagoga DOE Secundaria",
    principal: p("doe-secundaria", "María del Milagro Guerrero", "Psicopedagoga DOE Secundaria", 8),
  },
];
